services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: .
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      REDIS_URL: redis://redis:6379/0
      RQ_WORKER_CLASS: worker
      ENABLE_REAL_INFERENCE: "true"
      HF_LOCAL_FILES_ONLY: "true"
      HF_HOME: /opt/huggingface
      UPLOAD_DIR: /app/uploads
    depends_on:
      - redis
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
    command: python -m app.workers.run_worker
    environment:
      REDIS_URL: redis://redis:6379/0
      RQ_WORKER_CLASS: worker
      ENABLE_REAL_INFERENCE: "true"
      HF_LOCAL_FILES_ONLY: "true"
      HF_HOME: /opt/huggingface
      UPLOAD_DIR: /app/uploads
    depends_on:
      - redis
